/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, ContactShadows } from "@react-three/drei";
import { useControls } from "leva";

export default function ModelPenBookComponent(props) {
  const { nodes, materials } = useGLTF("./blue_pen_and_book.glb");

  // const { color, opacity, blur } = useControls("contact shadows", {
  //   color: "#000000",
  //   opacity: { value: 0.5, min: 0, max: 1 },
  //   blur: { value: 1, min: 0, max: 10 },
  // });

  return (
    <>
      <ContactShadows
        position={[0, -0.99, 0]}
        scale={10}
        resolution={512}
        far={5}
        color={"#000000"}
        opacity={0.5}
        blur={2}
        frames={1}
      />
      <mesh
        receiveShadow
        position={[1.5, -1, 1.5]}
        rotation-x={-Math.PI * 0.5}
        scale={20}
      >
        <planeGeometry />
        <meshStandardMaterial color='white' />
      </mesh>
      <group {...props} dispose={null}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Chrome.geometry}
          material={materials["metalic blue"]}
          rotation={[1.01, -0.39, 1.34]}
          scale={0.37}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Matte.geometry}
          material={materials.Matte}
          rotation={[1.01, -0.39, 1.34]}
          scale={0.37}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Glossy.geometry}
          material={materials.glossy}
          rotation={[1.01, -0.39, 1.34]}
          scale={0.37}
        />
        <group
          position={[0.34, 0.46, 1.9]}
          rotation={[-3.11, -0.03, -35]}
          scale={-1.35}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001.geometry}
            material={materials.blue}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001_1.geometry}
            material={materials.Material}
          />
        </group>
      </group>
    </>
  );
}

useGLTF.preload("./blue_pen_and_book.glb");
